controllers:
    resource: ../src/Controller/
    type: attribute

# Challenge-symfony-MVC
'app_lucky_number':
    path : /lucky/number
    controller : App\Controller\LuckyController::number


# Challenge-symfony-MVC
#'app_learning':
#path: /learning/about-me
#controller: App\Controller\LearningController::string